### ISSUE TITLE
Description at https://addons.mozilla.org/addon/minimal-github/

### ISSUE THREAD

**Issue by grahamperrin** [mesaugat/minimal-github#1]
I installed the extension but I see no difference in GitHub. 

Can you make https://addons.mozilla.org/addon/minimal-github/ more descriptive? 

Ideally please have a screenshot that shows a URL. 

Thanks

**Comment by mesaugat** [comment]
Sure, I will update the description. GitHub just updated it's UI and moved it's sidebar to the left which looks really bad IMO. This add-on just hides those sidebars so that we can focus on the GitHub feed instead.

**Comment by mesaugat** [comment]
@grahamperrin I have updated the description for the add-on and also included a short description in the repository itself. Thank you for the suggestion.
